### PR TITLE
tr into de

### PR DESCRIPTION
**Pull request by frju365**

### CODE REVIEW

**Comment by andersevenrud** [comment]
Is german one of your primary languages? I can probably get someone to proof-read this as I have a few friends that speak it natively.

**Comment by frju365** [comment]
yes. No, but I've C1 Level (university). I've German Abitur (~A-Level in Germany) too. :-) Well, what is most difficult (and in french too) is to translate English computer terms into another language where the translated word has not this sense.

**Comment by frju365** [comment]
But, yes, better to have another review (translation is not easy sometimes). ;)

**Comment by andersevenrud** [comment]
Aww. I forgot this one :blush:

**Pull request merged**
