### PR TITLE
Add a user menu

### PR DESCRIPTION
**Pull request by SpaceboyRoss01**

### CODE REVIEW

**Comment by SpaceboyRoss01** [comment]
I fixed the conflicts

**Comment by SpaceboyRoss01** [comment]
Adds #16

**Comment by andersevenrud** [comment]
Please split out the menu key binding to a separate pull-request

**Comment by SpaceboyRoss01** [comment]
@andersevenrud how?

**Comment by andersevenrud** [comment]
Use git branching

**Comment by SpaceboyRoss01** [comment]
Closing to switch to a different branch.

**Pull request closed without merging**
