### PR TITLE
More consistent positioning of menu

### PR DESCRIPTION
**Pull request by corwin-of-amber**
This is a reattempt to get #27.

### CODE REVIEW

**Comment by corwin-of-amber** [comment]
Ok I created a new one and still errors about using single quotes.

**Comment by corwin-of-amber** [comment]
I noticed that *all* single-quoted strings have errors in Codacy, it only reports the ones in the diff upon submitting a PR.
https://app.codacy.com/manual/os-js/osjs-panels/issues/index?bid=8129109

**Comment by andersevenrud** [comment]
Even though I disabled Cocay, it came back for unknown reasons. I disabled in in Github webhooks as well as the Codacy UI. I might just have to remove the repo link entirely or something.

I think the issue here is that Codacy don't read package.json, which is where I moved the eslint rules.

**Comment by andersevenrud** [comment]
Closing, because #27

**Pull request closed without merging**
